version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-hello-world"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16p69k896nmbu"
s3_prefix = "test-hello-world"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
